apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/FrancisRSweb/argo.git'
    targetRevision: HEAD
    path: 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  template:
    spec:
      applications:
        - name: app1
          project: default
          source:
            repoURL: 'https://github.com/FrancisRSweb/argo.git'
            path: 'app1'
            targetRevision: HEAD
          destination:
            server: 'https://kubernetes.default.svc'
            namespace: default
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
        
        
