apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  project: default
  source:
    repoURL: 'file:///ruta/a/tu/repo'
    targetRevision: HEAD
    path: my-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

